<template>
  <div v-if="!session" class="login-page">
    <header class="login-header"><strong>RK3588 报告中心</strong><span>患者录入与报告归档</span></header>
    <el-form class="login-panel" label-position="top" @submit.prevent="login">
      <h1>设备管理登录</h1><p>使用管理员或操作员账号进入本机报告中心</p>
      <el-form-item label="用户名"><el-input v-model="loginForm.username" autocomplete="username" /></el-form-item>
      <el-form-item label="密码"><el-input v-model="loginForm.password" type="password" show-password autocomplete="current-password" @keyup.enter="login" /></el-form-item>
      <el-alert v-if="loginError" :title="loginError" type="error" :closable="false" show-icon />
      <el-button type="primary" :loading="loginLoading" @click="login">登录</el-button>
    </el-form>
  </div>
  <div v-else class="app-shell">
    <header class="app-header"><div><strong>RK3588 报告中心</strong><span>{{ status.shadow_mode ? "影子验证" : "正式运行" }}</span></div><div class="header-right"><span>{{ session.username }} · {{ roleName }}</span><el-button text @click="logout">退出</el-button></div></header>
    <aside><el-menu :default-active="page" @select="selectPage"><el-menu-item index="dashboard"><el-icon><Monitor /></el-icon>工作台</el-menu-item><el-menu-item index="camera-patient"><el-icon><UserFilled /></el-icon>OCR患者字段</el-menu-item><el-menu-item index="entry-logs"><el-icon><Document /></el-icon>录入日志</el-menu-item><el-menu-item index="queue"><el-icon><List /></el-icon>患者队列</el-menu-item><el-menu-item index="reports"><el-icon><Document /></el-icon>报告中心</el-menu-item><el-menu-item index="profiles"><el-icon><SetUp /></el-icon>设备配置档</el-menu-item><el-menu-item index="connectors"><el-icon><Connection /></el-icon>连接器与上传</el-menu-item><el-menu-item index="system"><el-icon><Setting /></el-icon>系统管理</el-menu-item></el-menu></aside>
    <main>
      <section v-if="page === 'dashboard'">
        <PageHeader title="工作台"><el-button :icon="Refresh" @click="loadStatus">刷新</el-button></PageHeader>
        <div class="metric-grid"><div><span>摄像头观察</span><strong>{{ cameraCaptureTotal }}</strong></div><div><span>排队患者</span><strong>{{ count("sessions", "queued") }}</strong></div><div><span>等待报告</span><strong>{{ count("sessions", "awaiting_report") }}</strong></div><div><span>已归档报告</span><strong>{{ count("reports", "archived") }}</strong></div><div><span>待上传</span><strong>{{ count("uploads", "pending") + count("uploads", "retry_wait") }}</strong></div></div>
        <div class="section-band"><h2>当前处理</h2><div class="detail-grid" v-if="status.current_session"><span>患者</span><b>{{ status.current_session.patient_name || "待复核" }}</b><span>状态</span><StatusTag :value="status.current_session.status" /><span>检查项目</span><b>{{ status.current_session.exam_item || "-" }}</b></div><el-empty v-else description="当前没有正在处理的患者" :image-size="64" /></div>
        <div class="section-band table-band"><div class="band-tools"><h2>最近摄像头识别</h2><el-button :icon="Refresh" @click="loadStatus">刷新</el-button></div><el-table :data="cameraCaptures" empty-text="尚未收到摄像头 OCR 结果"><el-table-column label="接收时间" width="175"><template #default="s">{{ timeText(s.row.received_at) }}</template></el-table-column><el-table-column prop="capture_id" label="捕获ID" min-width="190" /><el-table-column label="OCR状态" width="150"><template #default="s"><StatusTag :value="s.row.status" /></template></el-table-column><el-table-column prop="block_count" label="文本块" width="90" /><el-table-column label="平均置信度" width="120"><template #default="s">{{ confidenceText(s.row.average_confidence) }}</template></el-table-column><el-table-column label="患者处理" width="145"><template #default="s"><StatusTag v-if="s.row.patient_result_status" :value="s.row.patient_result_status" /><span v-else>未生成</span></template></el-table-column></el-table></div>
        <div class="section-band"><h2>硬件与独立服务</h2><pre>{{ JSON.stringify(hardware, null, 2) }}</pre></div>
      </section>

      <CameraPatientConfig v-else-if="page === 'camera-patient'" :is-admin="isAdmin" />

      <EntryLogs v-else-if="page === 'entry-logs'" />

      <section v-else-if="page === 'queue'">
        <PageHeader title="患者队列"><el-button type="primary" :icon="Plus" @click="manualDialog = true">人工添加</el-button><el-button :icon="Refresh" @click="loadSessions">刷新</el-button></PageHeader>
        <div class="section-band table-band"><el-table :data="sessions" empty-text="暂无患者"><el-table-column prop="created_at" label="时间" width="175"><template #default="s">{{ timeText(s.row.created_at) }}</template></el-table-column><el-table-column label="患者" min-width="150"><template #default="s"><b>{{ s.row.patient_name || "待复核" }}</b><small>{{ s.row.patient_id || "" }}</small></template></el-table-column><el-table-column prop="exam_item" label="检查项目" min-width="150" /><el-table-column prop="source" label="来源" width="110" /><el-table-column label="状态" width="145"><template #default="s"><StatusTag :value="s.row.status" /></template></el-table-column><el-table-column label="操作" width="230"><template #default="s"><el-button v-if="s.row.status === 'review_required'" link type="primary" @click="reviewSession(s.row.id)">复核</el-button><el-button v-if="s.row.status === 'error'" link type="primary" @click="sessionAction(s.row.id, 'retry-entry')">重试录入</el-button><el-button v-if="s.row.status === 'awaiting_report'" link type="warning" @click="sessionAction(s.row.id, 'mark-missing')">标记缺失</el-button><el-button v-if="!['completed','cancelled','report_missing'].includes(s.row.status)" link type="danger" @click="sessionAction(s.row.id, 'cancel')">取消</el-button></template></el-table-column></el-table></div>
      </section>

      <section v-else-if="page === 'reports'">
        <PageHeader title="报告中心"><el-button :icon="Refresh" @click="loadReports">刷新</el-button></PageHeader>
        <div class="filter-row"><el-input v-model="reportFilters.patient_name" placeholder="患者姓名" clearable /><el-input v-model="reportFilters.patient_id" placeholder="患者ID" clearable /><el-input v-model="reportFilters.his_exam_no" placeholder="检查号" clearable /><el-select v-model="reportFilters.status" placeholder="归档状态" clearable><el-option v-for="item in ['archived','review_required','invalid','purged']" :key="item" :label="item" :value="item" /></el-select><el-button type="primary" :icon="Search" @click="loadReports">查询</el-button></div>
        <div class="section-band table-band"><el-table :data="reports.items" empty-text="暂无报告"><el-table-column label="归档时间" width="175"><template #default="s">{{ timeText(s.row.archived_at || s.row.created_at) }}</template></el-table-column><el-table-column label="患者" min-width="150"><template #default="s"><b>{{ s.row.patient_name || "未关联" }}</b><small>{{ s.row.patient_identifier || "" }}</small></template></el-table-column><el-table-column prop="exam_item" label="检查项目" min-width="150" /><el-table-column prop="source" label="来源" width="90" /><el-table-column label="归档" width="130"><template #default="s"><StatusTag :value="s.row.status" /></template></el-table-column><el-table-column label="上传" width="130"><template #default="s"><StatusTag :value="s.row.upload_status || '未配置'" /></template></el-table-column><el-table-column label="操作" width="240"><template #default="s"><el-button link type="primary" @click="openReport(s.row.id)">预览/下载</el-button><el-button link type="primary" @click="openReportDetail(s.row.id)">详情/修订</el-button><el-button v-if="['retry_wait','exhausted'].includes(s.row.upload_status)" link type="warning" @click="retryUpload(s.row.id)">重试</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="reports.page" v-model:page-size="reports.page_size" :total="reports.total" layout="total, prev, pager, next" @current-change="loadReports" /></div>
      </section>

      <section v-else-if="page === 'profiles'">
        <PageHeader title="设备配置档"><el-button v-if="isAdmin" type="primary" :icon="Plus" @click="createProfile">新建配置档</el-button><el-button :icon="Refresh" @click="loadProfiles">刷新</el-button></PageHeader>
        <div class="section-band table-band"><el-table :data="profiles"><el-table-column prop="name" label="名称" /><el-table-column prop="version" label="版本" width="90" /><el-table-column label="患者模式"><template #default="s">{{ s.row.config?.patient_input_mode }}</template></el-table-column><el-table-column label="报告来源" width="110"><template #default="s">{{ s.row.config?.report_source }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag v-if="s.row.active" type="success">当前</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="editProfile(s.row.id)">编辑</el-button></template></el-table-column></el-table></div>
        <div v-if="selectedProfile" class="section-band editor"><h2>草稿编辑</h2><el-alert title="保存不会影响运行；测试通过后发布，新版本只作用于下一位患者。" type="info" :closable="false" /><el-input v-model="profileJson" type="textarea" :rows="20" spellcheck="false" /><div class="editor-actions"><el-button :icon="CircleCheck" @click="testProfile">测试</el-button><el-button type="primary" :disabled="!isAdmin" @click="saveProfile">保存草稿</el-button><el-button type="success" :disabled="!isAdmin" @click="publishProfile">发布</el-button></div></div>
      </section>

      <section v-else-if="page === 'connectors'">
        <PageHeader title="连接器与上传"><el-button v-if="isAdmin" type="primary" :icon="Plus" @click="connectorDialog = true">新建</el-button><el-button :icon="Refresh" @click="loadConnectors">刷新</el-button></PageHeader>
        <el-alert v-if="!isAdmin" title="连接器配置仅管理员可见。" type="info" :closable="false" /><div v-else class="section-band table-band"><el-table :data="connectors"><el-table-column prop="name" label="名称" /><el-table-column prop="type" label="类型" width="150" /><el-table-column label="接口地址" min-width="260"><template #default="s">{{ s.row.config?.endpoint }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.enabled ? 'success' : 'info'">{{ s.row.enabled ? "启用" : "停用" }}</el-tag></template></el-table-column><el-table-column label="操作" width="120"><template #default="s"><el-button v-if="['sql_proxy','rest_json'].includes(s.row.type)" link type="primary" @click="testConnector(s.row.id)">脱敏测试</el-button></template></el-table-column></el-table></div>
      </section>

      <section v-else>
        <PageHeader title="系统管理" />
        <div class="section-band form-band"><h2>修改密码</h2><el-form label-width="120px"><el-form-item label="当前密码"><el-input v-model="passwordForm.current_password" type="password" show-password /></el-form-item><el-form-item label="新密码"><el-input v-model="passwordForm.new_password" type="password" show-password /></el-form-item><el-form-item><el-button type="primary" @click="changePassword">更新密码</el-button></el-form-item></el-form></div>
        <el-alert v-if="!isAdmin" title="系统管理仅管理员可用。" type="warning" :closable="false" />
        <template v-else><div class="section-band table-band"><div class="band-tools"><h2>用户</h2><el-button type="primary" :icon="Plus" @click="createUser">新增操作员</el-button></div><el-table :data="users"><el-table-column prop="username" label="用户名" /><el-table-column prop="role" label="角色" /><el-table-column label="状态"><template #default="s"><StatusTag :value="s.row.enabled ? 'enabled' : 'disabled'" /></template></el-table-column><el-table-column label="首次改密"><template #default="s">{{ s.row.must_change ? '是' : '否' }}</template></el-table-column></el-table></div><div class="section-band table-band"><div class="band-tools"><h2>归档 API 令牌</h2><el-button type="primary" :icon="Plus" @click="createToken">新建令牌</el-button></div><el-table :data="tokens"><el-table-column prop="name" label="名称" /><el-table-column label="权限"><template #default="s">{{ s.row.scopes.join(', ') }}</template></el-table-column><el-table-column label="最后使用"><template #default="s">{{ timeText(s.row.last_used_at) }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button v-if="s.row.enabled" link type="danger" @click="revokeToken(s.row.id)">撤销</el-button></template></el-table-column></el-table></div><div class="section-band form-band"><h2>存储维护</h2><el-form label-width="140px"><el-form-item label="本地保留天数"><el-input-number v-model="retentionDays" :min="1" :max="3650" /></el-form-item><el-form-item><el-button @click="backupDatabase">备份数据库</el-button><el-button @click="cleanup(false)">清理预览</el-button><el-button type="danger" @click="cleanup(true)">确认执行</el-button></el-form-item></el-form><pre v-if="cleanupResult">{{ JSON.stringify(cleanupResult, null, 2) }}</pre></div><div class="section-band"><div class="band-tools"><h2>审计日志</h2><el-button :icon="Refresh" @click="loadAudit">刷新</el-button></div><el-table :data="audit" max-height="440"><el-table-column label="时间" width="175"><template #default="s">{{ timeText(s.row.created_at) }}</template></el-table-column><el-table-column prop="actor" label="账号" width="110" /><el-table-column prop="action" label="动作" /><el-table-column prop="object_type" label="对象" width="120" /><el-table-column prop="object_id" label="对象ID" /></el-table></div></template>
      </section>
    </main>

    <el-dialog v-model="manualDialog" title="人工添加患者" width="480px"><el-form label-width="100px"><el-form-item label="患者姓名"><el-input v-model="manualPatient.patient_name" /></el-form-item><el-form-item label="患者ID"><el-input v-model="manualPatient.patient_id" /></el-form-item><el-form-item label="检查项目"><el-input v-model="manualPatient.exam_item" /></el-form-item></el-form><template #footer><el-button @click="manualDialog=false">取消</el-button><el-button type="primary" @click="submitManual">加入队列</el-button></template></el-dialog>
    <el-dialog v-model="reviewDialog" title="患者复核" width="720px"><el-radio-group v-model="candidateIndex" class="candidate-list"><el-radio v-for="(item,index) in reviewCandidates" :key="index" :value="index" border><b>{{ item.patient_name || '未知患者' }}</b><span>{{ item.patient_id || item.his_exam_no || item.report_no || '' }} · {{ item.exam_item || '' }}</span></el-radio></el-radio-group><template #footer><el-button @click="reviewDialog=false">取消</el-button><el-button type="primary" :disabled="candidateIndex < 0" @click="approveCandidate">确认患者</el-button></template></el-dialog>
    <el-dialog v-model="connectorDialog" title="新建连接器" width="680px"><el-form label-width="110px"><el-form-item label="名称"><el-input v-model="connectorForm.name" /></el-form-item><el-form-item label="类型"><el-select v-model="connectorForm.type"><el-option v-for="item in ['sql_proxy','rest_json','report_multipart','rest_multipart']" :key="item" :value="item" /></el-select></el-form-item><el-form-item label="配置 JSON"><el-input v-model="connectorForm.configText" type="textarea" :rows="12" /></el-form-item></el-form><template #footer><el-button @click="connectorDialog=false">取消</el-button><el-button type="primary" @click="submitConnector">保存</el-button></template></el-dialog>
    <el-dialog v-model="reportDialog" title="报告详情与元数据修订" width="760px"><el-descriptions v-if="reportDetail.id" :column="2" border><el-descriptions-item label="报告ID">{{ reportDetail.id }}</el-descriptions-item><el-descriptions-item label="SHA-256"><span class="hash-text">{{ reportDetail.sha256 }}</span></el-descriptions-item><el-descriptions-item label="归档状态">{{ reportDetail.status }}</el-descriptions-item><el-descriptions-item label="上传状态">{{ reportDetail.upload_status || '未配置' }}</el-descriptions-item></el-descriptions><el-form label-width="110px" class="report-edit"><el-form-item label="元数据 JSON"><el-input v-model="reportMetadataText" type="textarea" :rows="11" /></el-form-item><el-form-item label="修订原因"><el-input v-model="reportRevisionReason" placeholder="上传后更正必须填写原因" /></el-form-item><el-form-item v-if="!reportDetail.session_id" label="关联会话"><el-select v-model="assignSessionId" filterable placeholder="选择等待或报告缺失的患者会话"><el-option v-for="item in assignableSessions" :key="item.id" :label="`${item.patient_name || '未知患者'} · ${item.status} · ${item.id.slice(0,8)}`" :value="item.id" /></el-select><el-button :disabled="!assignSessionId" @click="assignCurrentReport">关联</el-button></el-form-item></el-form><h3>修订历史</h3><el-timeline><el-timeline-item v-for="item in reportRevisions" :key="item.id" :timestamp="timeText(item.created_at)"><b>版本 {{ item.version }}</b> · {{ item.created_by }}<span v-if="item.reason"> · {{ item.reason }}</span></el-timeline-item></el-timeline><template #footer><el-button @click="reportDialog=false">关闭</el-button><el-button type="primary" @click="saveReportMetadata">保存新修订</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { computed, defineComponent, h, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { CircleCheck, Connection, Document, List, Monitor, Plus, Refresh, Search, Setting, SetUp, UserFilled } from "@element-plus/icons-vue";
import { api, setCsrf } from "./api";
import CameraPatientConfig from "./CameraPatientConfig.vue";
import EntryLogs from "./EntryLogs.vue";

const PageHeader = defineComponent({ props: { title: String }, setup(props,{slots}){return()=>h('div',{class:'page-header'},[h('h1',props.title),h('div',{class:'page-actions'},slots.default?.())])} });
const StatusTag = defineComponent({ props:{value:String},setup(props){const types={completed:'success',accepted:'success',archived:'success',uploaded:'success',awaiting_report:'warning',review_required:'warning',retry_wait:'warning',rejected:'danger',error:'danger',invalid:'danger',exhausted:'danger'};return()=>h('span',{class:['status-tag',types[props.value]||'info']},props.value||'-')}});
const session=ref(null),loginLoading=ref(false),loginError=ref(''),page=ref('dashboard');const loginForm=reactive({username:'admin',password:''});const status=reactive({shadow_mode:true,counts:{sessions:{},reports:{},uploads:{},camera_captures:{}},current_session:null});const hardware=ref({});const cameraCaptures=ref([]);const sessions=ref([]);const reports=reactive({items:[],page:1,page_size:20,total:0});const reportFilters=reactive({patient_name:'',patient_id:'',his_exam_no:'',status:''});const profiles=ref([]),selectedProfile=ref(0),profileJson=ref('');const connectors=ref([]),audit=ref([]),users=ref([]),tokens=ref([]),retentionDays=ref(90),cleanupResult=ref(null);const passwordForm=reactive({current_password:'',new_password:''});const manualDialog=ref(false),manualPatient=reactive({patient_name:'',patient_id:'',exam_item:''});const reviewDialog=ref(false),reviewSessionId=ref(''),reviewCandidates=ref([]),candidateIndex=ref(-1);const connectorDialog=ref(false),connectorForm=reactive({name:'',type:'rest_json',configText:'{"endpoint":"http://","method":"POST","request":{"code":"{{query}}"},"records_path":"$.data","field_mapping":{}}'});const reportDialog=ref(false),reportDetail=ref({}),reportRevisions=ref([]),reportMetadataText=ref('{}'),reportRevisionReason=ref(''),assignSessionId=ref(''),assignableSessions=ref([]);
const isAdmin=computed(()=>session.value?.role==='admin'),roleName=computed(()=>isAdmin.value?'管理员':'操作员'),cameraCaptureTotal=computed(()=>Object.values(status.counts?.camera_captures||{}).reduce((sum,value)=>sum+Number(value||0),0));function count(group,key){return status.counts?.[group]?.[key]||0}function timeText(value){return value?new Date(value*1000).toLocaleString():'-'}function confidenceText(value){return Number.isFinite(value)?`${(value*100).toFixed(1)}%`:'-'}async function guarded(work){try{return await work()}catch(error){if(error.status===401)session.value=null;ElMessage.error(error.message);throw error}}
async function login(){loginLoading.value=true;loginError.value='';try{const data=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify(loginForm)});setCsrf(data.csrf);session.value=data;if(data.must_change)page.value='system';await loadStatus()}catch(error){loginError.value=error.message}finally{loginLoading.value=false}}async function logout(){await guarded(()=>api('/api/v1/auth/logout',{method:'POST',body:'{}'}));session.value=null;setCsrf('')}async function restore(){try{const data=await api('/api/v1/auth/session');setCsrf(data.csrf);session.value=data;if(data.must_change)page.value='system';await loadStatus()}catch{session.value=null}}
function selectPage(value){page.value=value;({queue:loadSessions,reports:loadReports,profiles:loadProfiles,connectors:loadConnectors,system:loadSystem,dashboard:loadStatus}[value])?.()}async function loadStatus(){const [s,h,c]=await Promise.all([guarded(()=>api('/api/v1/status')),guarded(()=>api('/api/v1/hardware')),guarded(()=>api('/api/v1/camera-captures?limit=10'))]);Object.assign(status,s);hardware.value=h;cameraCaptures.value=c.items}async function loadSessions(){const d=await guarded(()=>api('/api/v1/sessions'));sessions.value=d.items}async function submitManual(){await guarded(()=>api('/api/v1/intake',{method:'POST',body:JSON.stringify({mode:'manual',patient:manualPatient})}));manualDialog.value=false;Object.assign(manualPatient,{patient_name:'',patient_id:'',exam_item:''});ElMessage.success('已加入队列');loadSessions()}async function sessionAction(id,action){if(action==='cancel'||action==='mark-missing')await ElMessageBox.confirm('确认执行此操作？','操作确认',{type:'warning'});await guarded(()=>api(`/api/v1/sessions/${id}/${action}`,{method:'POST',body:'{}'}));loadSessions()}async function reviewSession(id){const d=await guarded(()=>api('/api/v1/sessions/'+id));reviewSessionId.value=id;reviewCandidates.value=d.review_candidates||[];candidateIndex.value=-1;reviewDialog.value=true}async function approveCandidate(){await guarded(()=>api(`/api/v1/sessions/${reviewSessionId.value}/approve`,{method:'POST',body:JSON.stringify({candidate_index:candidateIndex.value})}));reviewDialog.value=false;loadSessions()}
async function loadReports(){const q=new URLSearchParams({...reportFilters,page:String(reports.page),page_size:String(reports.page_size)});Object.assign(reports,await guarded(()=>api('/api/v1/reports?'+q)))}function openReport(id){window.open(`/api/v1/reports/${id}/content`,'_blank')}async function openReportDetail(id){const [detail,revisions,sessionData]=await Promise.all([guarded(()=>api('/api/v1/reports/'+id)),guarded(()=>api(`/api/v1/reports/${id}/revisions`)),guarded(()=>api('/api/v1/sessions?limit=500'))]);reportDetail.value=detail;reportRevisions.value=revisions.items;reportMetadataText.value=JSON.stringify(detail.metadata||{},null,2);reportRevisionReason.value='';assignSessionId.value='';assignableSessions.value=sessionData.items.filter(x=>['awaiting_report','report_missing'].includes(x.status)&&!x.report_id);reportDialog.value=true}async function saveReportMetadata(){const metadata=JSON.parse(reportMetadataText.value);reportDetail.value=await guarded(()=>api(`/api/v1/reports/${reportDetail.value.id}/metadata`,{method:'PATCH',body:JSON.stringify({metadata,reason:reportRevisionReason.value})}));const revisions=await guarded(()=>api(`/api/v1/reports/${reportDetail.value.id}/revisions`));reportRevisions.value=revisions.items;ElMessage.success('元数据修订已保存');loadReports()}async function assignCurrentReport(){reportDetail.value=await guarded(()=>api(`/api/v1/reports/${reportDetail.value.id}/assign`,{method:'POST',body:JSON.stringify({session_id:assignSessionId.value})}));ElMessage.success('报告已关联');loadReports()}async function retryUpload(id){await guarded(()=>api(`/api/v1/reports/${id}/retry-upload`,{method:'POST',body:'{}'}));ElMessage.success('已加入重试');loadReports()}
async function loadProfiles(){const d=await guarded(()=>api('/api/v1/profiles'));profiles.value=d.items}async function editProfile(id){const d=await guarded(()=>api('/api/v1/profiles/'+id));selectedProfile.value=id;const revision=d.revisions.find(x=>x.status==='draft')||d.revisions[0];profileJson.value=JSON.stringify(revision.config,null,2)}async function createProfile(){const {value:name}=await ElMessageBox.prompt('请输入配置档名称','新建配置档');const config={patient_input_mode:'manual',camera_intake_enabled:false,camera_patient_enabled:false,patient_connector_id:null,exam_item_filter:'',auto_entry_enabled:false,report_source:'msc',field_resolver:{provider:'rules',fields:[]},hid:{template_path:'',actions:[]},upload_target_id:null};const d=await guarded(()=>api('/api/v1/profiles',{method:'POST',body:JSON.stringify({name,config})}));await loadProfiles();editProfile(d.id)}async function saveProfile(){const config=JSON.parse(profileJson.value);await guarded(()=>api(`/api/v1/profiles/${selectedProfile.value}/draft`,{method:'PUT',body:JSON.stringify({config})}));ElMessage.success('草稿已保存');loadProfiles()}async function testProfile(){const config=JSON.parse(profileJson.value);await guarded(()=>api(`/api/v1/profiles/${selectedProfile.value}/test`,{method:'POST',body:JSON.stringify({config})}));ElMessage.success('语法与依赖测试通过')}async function publishProfile(){await saveProfile();await guarded(()=>api(`/api/v1/profiles/${selectedProfile.value}/publish`,{method:'POST',body:'{}'}));ElMessage.success('配置已发布');loadProfiles()}
async function loadConnectors(){if(!isAdmin.value)return;const d=await guarded(()=>api('/api/v1/connectors'));connectors.value=d.items}async function submitConnector(){const config=JSON.parse(connectorForm.configText);await guarded(()=>api('/api/v1/connectors',{method:'POST',body:JSON.stringify({name:connectorForm.name,type:connectorForm.type,config})}));connectorDialog.value=false;loadConnectors()}async function testConnector(id){const {value:query}=await ElMessageBox.prompt('输入人工脱敏的测试号码','连接测试');const d=await guarded(()=>api(`/api/v1/connectors/${id}/test`,{method:'POST',body:JSON.stringify({query})}));ElMessage.success(`连接成功，返回 ${d.record_count} 条记录`)}async function changePassword(){await guarded(()=>api('/api/v1/auth/password',{method:'POST',body:JSON.stringify(passwordForm)}));Object.assign(passwordForm,{current_password:'',new_password:''});session.value.must_change=false;ElMessage.success('密码已更新')}async function loadSystem(){if(!isAdmin.value)return;const [u,t,a]=await Promise.all([guarded(()=>api('/api/v1/users')),guarded(()=>api('/api/v1/tokens')),guarded(()=>api('/api/v1/audit'))]);users.value=u.items;tokens.value=t.items;audit.value=a.items}async function createUser(){const {value:username}=await ElMessageBox.prompt('用户名','新增操作员');const {value:password}=await ElMessageBox.prompt('初始密码（至少8位）','新增操作员',{inputType:'password'});await guarded(()=>api('/api/v1/users',{method:'POST',body:JSON.stringify({username,password,role:'operator',must_change:true})}));ElMessage.success('操作员已创建');loadSystem()}async function createToken(){const {value:name}=await ElMessageBox.prompt('令牌名称','新建归档 API 令牌');const data=await guarded(()=>api('/api/v1/tokens',{method:'POST',body:JSON.stringify({name,scopes:['reports:read','reports:download']})}));await ElMessageBox.alert(data.token,'令牌只显示一次，请立即安全保存',{confirmButtonText:'已保存'});loadSystem()}async function revokeToken(id){await ElMessageBox.confirm('撤销后该令牌立即失效，确认？','撤销令牌',{type:'warning'});await guarded(()=>api('/api/v1/tokens/'+id,{method:'DELETE',body:'{}'}));loadSystem()}async function backupDatabase(){const data=await guarded(()=>api('/api/v1/maintenance/backup',{method:'POST',body:'{}'}));ElMessage.success(`数据库已备份，大小 ${data.size} 字节`);loadAudit()}async function cleanup(execute){if(execute)await ElMessageBox.confirm('仅删除已上传成功且超过保留期的 PDF，确认执行？','清理确认',{type:'warning'});cleanupResult.value=await guarded(()=>api('/api/v1/maintenance/cleanup',{method:'POST',body:JSON.stringify({retention_days:retentionDays.value,execute})}))}async function loadAudit(){if(!isAdmin.value)return;const d=await guarded(()=>api('/api/v1/audit'));audit.value=d.items}
onMounted(restore);
</script>
